[[main]]
  name = 'Moebius'
  pageRef = '/'
  weight = 10

[[main]]
  name = 'Moebius SOL'
  pageRef = '/moebius-sol'
  weight = 40

[[main]]
  name = 'Länkar'
  pageRef = '/links'
  weight = 50

[[main]]
  name = 'Arkiv'
  pageRef = '/arkiv'
  weight = 60

[[main]]
  name = 'Donera'
  pageRef = '/donera'
  weight = 70

  [[main]]
name = 'Guide till matrisen'
pageRef = '/matrisen'
weight = 80
