[[main]]
  name = 'Moebius'
  pageRef = '/'
  weight = 10
[[main]]
  name = 'Möbius SOL'
  pageRef = '/moebius-sol'
  weight = 40

[[main]]
  name = 'Links'
  pageRef = '/links'
  weight = 50

[[main]]
  name = 'Archive'
  pageRef = '/arkiv'
  weight = 60

[[main]]
  name = 'Donate'
  pageRef = '/donera'
  weight = 70

#[[main]]
#name = 'Guide to the matrix'
#pageRef = '/matrisen'
#weight = 80
